apiVersion: v1
kind: Secret
metadata:
  name: {{ template "supervisor" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  SUPERVISOR_USERNAME: {{ .Values.php.supervisor.basicAuth.username | b64enc | quote }}
  SUPERVISOR_PASSWORD: {{ .Values.php.supervisor.basicAuth.password | b64enc | quote }}