apiVersion: v1
kind: Service
metadata:
  name: {{ template "supervisor" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: supervisor
      port: 9000
      targetPort: 9000
  selector:
    {{- include "matchLabels" . | nindent 4 }}
    component: supervisor