apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    {{- include "matchLabels" . | nindent 4 }}
    component: nginx
