version: '3.4'

services:
  fpm:
    command: ['fpm']
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: php
    healthcheck:
      test: ['CMD', 'docker-healthcheck', 'fpm']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  supervisor:
    command: ['supervisor']
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: php
    healthcheck:
      test: ['CMD', 'docker-healthcheck', 'supervisor']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nginx
    healthcheck:
      test: ['CMD', 'docker-healthcheck']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - fpm