name: Docker

on:
  push:
    branches:
      - master
env:
  PHP_IMAGE: vuongxuongminh/docker-helm-yii-php
  NGINX_IMAGE: vuongxuongminh/docker-helm-yii-nginx

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin
        
      - name: Build images
        run: |
            docker-compose -f docker-compose.yaml -f docker-compose.override.yaml build
            docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml build
            
      - name: Push image
        run: |
            docker-compose -f docker-compose.yaml -f docker-compose.override.yaml push
            docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml push

